# Generated by Django 4.2.30 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_github_profile_user_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=50),
        ),
    ]
