from django.core.management.base import BaseCommand

from jobs.models import JobRole


JOB_ROLES = [
    {
        'title': 'Python Developer',
        'description': 'Build backend services, APIs, automation scripts, and maintain Python applications.',
        'required_skills': ['Python', 'REST API', 'PostgreSQL', 'Git'],
        'keywords': ['python', 'api', 'backend', 'automation', 'postgresql'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Django Developer',
        'description': 'Develop Django apps, REST endpoints, authentication flows, and database-backed services.',
        'required_skills': ['Python', 'Django', 'REST API', 'PostgreSQL', 'JWT'],
        'keywords': ['django', 'drf', 'python', 'postgresql', 'jwt'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'React Developer',
        'description': 'Build responsive React interfaces, reusable components, and frontend state flows.',
        'required_skills': ['JavaScript', 'React', 'HTML', 'CSS', 'Tailwind'],
        'keywords': ['react', 'frontend', 'vite', 'tailwind', 'javascript'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Full Stack Developer',
        'description': 'Own frontend and backend features across APIs, databases, and UI delivery.',
        'required_skills': ['Python', 'Django', 'React', 'PostgreSQL', 'Git'],
        'keywords': ['full stack', 'react', 'django', 'api', 'database'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Backend Developer',
        'description': 'Design APIs, business logic, integrations, and scalable backend services.',
        'required_skills': ['Python', 'Django', 'REST API', 'PostgreSQL', 'Docker'],
        'keywords': ['backend', 'api', 'microservices', 'django', 'docker'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Frontend Developer',
        'description': 'Create polished frontend experiences with strong UX, responsiveness, and performance.',
        'required_skills': ['JavaScript', 'React', 'HTML', 'CSS', 'Tailwind'],
        'keywords': ['frontend', 'react', 'responsive', 'ui', 'css'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Data Analyst',
        'description': 'Analyze datasets, build reports and dashboards, and deliver business insights.',
        'required_skills': ['Python', 'Pandas', 'NumPy', 'Data Analysis', 'SQL'],
        'keywords': ['analytics', 'sql', 'pandas', 'dashboard', 'reporting'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Machine Learning Engineer',
        'description': 'Train, evaluate, and deploy machine learning models for production use cases.',
        'required_skills': ['Python', 'Machine Learning', 'Scikit-learn', 'TensorFlow', 'Docker'],
        'keywords': ['ml', 'model', 'training', 'deployment', 'scikit-learn'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'AI/ML Engineer',
        'description': 'Build AI-powered systems using machine learning, NLP, and model-serving pipelines.',
        'required_skills': ['Python', 'Machine Learning', 'NLP', 'PyTorch', 'Docker'],
        'keywords': ['ai', 'ml', 'nlp', 'pytorch', 'inference'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'DevOps Engineer',
        'description': 'Automate deployments, manage cloud infrastructure, and improve delivery reliability.',
        'required_skills': ['Docker', 'AWS', 'Linux', 'Git', 'CI/CD'],
        'keywords': ['devops', 'docker', 'aws', 'pipeline', 'infrastructure'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Software Engineer',
        'description': 'Build scalable software systems with strong coding, problem-solving, and collaboration skills.',
        'required_skills': ['Python', 'JavaScript', 'Git', 'REST API', 'SQL'],
        'keywords': ['software engineer', 'coding', 'system design', 'api', 'sql'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Data Scientist',
        'description': 'Analyze data, build predictive models, and translate insights into business impact.',
        'required_skills': ['Python', 'Pandas', 'NumPy', 'Machine Learning', 'SQL'],
        'keywords': ['data science', 'modeling', 'python', 'sql', 'analytics'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Business Analyst',
        'description': 'Bridge business requirements and technical execution using analysis, reporting, and documentation.',
        'required_skills': ['SQL', 'Data Analysis', 'Excel', 'Reporting', 'Communication'],
        'keywords': ['business analysis', 'reporting', 'stakeholders', 'sql', 'requirements'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Cloud Engineer',
        'description': 'Design and maintain cloud-native systems, deployments, and infrastructure automation.',
        'required_skills': ['AWS', 'Docker', 'Linux', 'Python', 'Git'],
        'keywords': ['cloud', 'aws', 'deployment', 'infrastructure', 'automation'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'QA Engineer',
        'description': 'Test software quality through automation, regression coverage, and release validation.',
        'required_skills': ['Testing', 'Automation', 'Python', 'Selenium', 'Git'],
        'keywords': ['qa', 'testing', 'automation', 'selenium', 'quality'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'UI/UX Developer',
        'description': 'Translate product ideas into usable, accessible, and polished user experiences.',
        'required_skills': ['HTML', 'CSS', 'JavaScript', 'React', 'Responsive Design'],
        'keywords': ['ui', 'ux', 'design system', 'frontend', 'responsive'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Node.js Developer',
        'description': 'Develop backend services and APIs using JavaScript and Node.js ecosystems.',
        'required_skills': ['JavaScript', 'Node.js', 'Express', 'MongoDB', 'REST API'],
        'keywords': ['node', 'express', 'backend', 'mongodb', 'api'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'FastAPI Developer',
        'description': 'Build modern Python APIs with FastAPI, async workflows, and performant services.',
        'required_skills': ['Python', 'FastAPI', 'REST API', 'PostgreSQL', 'Docker'],
        'keywords': ['fastapi', 'python', 'async', 'api', 'postgresql'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'NLP Engineer',
        'description': 'Build text-processing, language models, and NLP pipelines for AI applications.',
        'required_skills': ['Python', 'NLP', 'Machine Learning', 'PyTorch', 'TensorFlow'],
        'keywords': ['nlp', 'language model', 'text processing', 'pytorch', 'ai'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'MERN Stack Developer',
        'description': 'Build full-stack JavaScript applications with MongoDB, Express, React, and Node.js.',
        'required_skills': ['MongoDB', 'Express', 'React', 'Node.js', 'JavaScript'],
        'keywords': ['mern', 'react', 'node', 'mongodb', 'express'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Java Developer',
        'description': 'Develop enterprise applications using Java, Spring Boot, and related frameworks.',
        'required_skills': ['Java', 'Spring Boot', 'REST API', 'MySQL', 'Maven'],
        'keywords': ['java', 'spring', 'enterprise', 'backend', 'api'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Flutter Developer',
        'description': 'Build cross-platform mobile applications using Flutter and Dart.',
        'required_skills': ['Flutter', 'Dart', 'Mobile Development', 'Firebase', 'REST API'],
        'keywords': ['flutter', 'mobile', 'dart', 'cross-platform', 'app'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'iOS Developer',
        'description': 'Develop native iOS applications using Swift and iOS frameworks.',
        'required_skills': ['Swift', 'iOS', 'Xcode', 'UIKit', 'REST API'],
        'keywords': ['ios', 'swift', 'mobile', 'apple', 'app store'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Android Developer',
        'description': 'Build native Android applications using Kotlin and Android SDK.',
        'required_skills': ['Kotlin', 'Android', 'Java', 'Gradle', 'REST API'],
        'keywords': ['android', 'kotlin', 'mobile', 'google play', 'app'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Go Developer',
        'description': 'Build high-performance backend services and microservices using Go.',
        'required_skills': ['Go', 'Microservices', 'REST API', 'PostgreSQL', 'Docker'],
        'keywords': ['go', 'golang', 'microservices', 'backend', 'performance'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Rust Developer',
        'description': 'Build systems programming and high-performance applications using Rust.',
        'required_skills': ['Rust', 'Systems Programming', 'Memory Management', 'Git', 'CLI'],
        'keywords': ['rust', 'systems', 'performance', 'memory', 'cli'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'PHP Developer',
        'description': 'Develop web applications using PHP, Laravel, and related frameworks.',
        'required_skills': ['PHP', 'Laravel', 'MySQL', 'REST API', 'Composer'],
        'keywords': ['php', 'laravel', 'web', 'backend', 'mysql'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Ruby on Rails Developer',
        'description': 'Build web applications using Ruby on Rails framework and Ruby ecosystem.',
        'required_skills': ['Ruby', 'Rails', 'PostgreSQL', 'REST API', 'Git'],
        'keywords': ['ruby', 'rails', 'web', 'mvc', 'postgresql'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Vue.js Developer',
        'description': 'Build reactive user interfaces using Vue.js and related ecosystem tools.',
        'required_skills': ['JavaScript', 'Vue.js', 'HTML', 'CSS', 'Vuex'],
        'keywords': ['vue', 'frontend', 'javascript', 'reactive', 'spa'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Angular Developer',
        'description': 'Develop enterprise-scale web applications using Angular and TypeScript.',
        'required_skills': ['TypeScript', 'Angular', 'RxJS', 'HTML', 'CSS'],
        'keywords': ['angular', 'typescript', 'frontend', 'enterprise', 'spa'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Svelte Developer',
        'description': 'Build modern web applications using Svelte framework for optimal performance.',
        'required_skills': ['JavaScript', 'Svelte', 'HTML', 'CSS', 'SvelteKit'],
        'keywords': ['svelte', 'frontend', 'javascript', 'performance', 'spa'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Next.js Developer',
        'description': 'Build full-stack React applications with Next.js framework for SSR and SSG.',
        'required_skills': ['React', 'Next.js', 'JavaScript', 'TypeScript', 'Node.js'],
        'keywords': ['next.js', 'react', 'ssr', 'full stack', 'seo'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'GraphQL Developer',
        'description': 'Design and implement GraphQL APIs and schemas for efficient data fetching.',
        'required_skills': ['GraphQL', 'JavaScript', 'Apollo', 'Node.js', 'REST API'],
        'keywords': ['graphql', 'api', 'apollo', 'schema', 'query'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'WordPress Developer',
        'description': 'Build and customize WordPress websites with themes and plugins.',
        'required_skills': ['PHP', 'WordPress', 'HTML', 'CSS', 'JavaScript'],
        'keywords': ['wordpress', 'php', 'cms', 'theme', 'plugin'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Shopify Developer',
        'description': 'Build e-commerce stores and custom themes on Shopify platform.',
        'required_skills': ['Shopify', 'Liquid', 'HTML', 'CSS', 'JavaScript'],
        'keywords': ['shopify', 'ecommerce', 'liquid', 'theme', 'store'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Salesforce Developer',
        'description': 'Develop custom applications and integrations on Salesforce platform.',
        'required_skills': ['Apex', 'Visualforce', 'SOQL', 'JavaScript', 'Salesforce'],
        'keywords': ['salesforce', 'apex', 'crm', 'cloud', 'integration'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'SAP Developer',
        'description': 'Develop and customize SAP enterprise applications and modules.',
        'required_skills': ['SAP', 'ABAP', 'SQL', 'Java', 'Integration'],
        'keywords': ['sap', 'abap', 'enterprise', 'erp', 'module'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Tableau Developer',
        'description': 'Create interactive dashboards and visualizations using Tableau.',
        'required_skills': ['Tableau', 'Data Visualization', 'SQL', 'Excel', 'Analytics'],
        'keywords': ['tableau', 'visualization', 'dashboard', 'bi', 'analytics'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Power BI Developer',
        'description': 'Build business intelligence solutions and reports using Power BI.',
        'required_skills': ['Power BI', 'DAX', 'SQL', 'Excel', 'Data Modeling'],
        'keywords': ['power bi', 'bi', 'dax', 'reporting', 'analytics'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'ETL Developer',
        'description': 'Design and implement ETL processes for data integration and transformation.',
        'required_skills': ['Python', 'SQL', 'ETL', 'Data Warehousing', 'Apache Airflow'],
        'keywords': ['etl', 'data warehouse', 'pipeline', 'integration', 'airflow'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Database Administrator',
        'description': 'Manage, optimize, and secure database systems for performance and reliability.',
        'required_skills': ['SQL', 'PostgreSQL', 'MySQL', 'Database Administration', 'Backup'],
        'keywords': ['dba', 'database', 'sql', 'optimization', 'backup'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Site Reliability Engineer',
        'description': 'Ensure system reliability, availability, and performance through engineering practices.',
        'required_skills': ['Linux', 'Python', 'Monitoring', 'Incident Management', 'AWS'],
        'keywords': ['sre', 'reliability', 'monitoring', 'incidents', 'uptime'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Security Engineer',
        'description': 'Design and implement security solutions to protect systems and data.',
        'required_skills': ['Security', 'Penetration Testing', 'Python', 'Networking', 'CI/CD'],
        'keywords': ['security', 'cybersecurity', 'penetration', 'network', 'compliance'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Blockchain Developer',
        'description': 'Build decentralized applications and smart contracts using blockchain technologies.',
        'required_skills': ['Solidity', 'Blockchain', 'Web3', 'JavaScript', 'Smart Contracts'],
        'keywords': ['blockchain', 'web3', 'solidity', 'smart contracts', 'defi'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Game Developer',
        'description': 'Develop video games using game engines and programming languages.',
        'required_skills': ['Unity', 'C#', 'Game Development', '3D', 'Physics'],
        'keywords': ['game', 'unity', 'c#', '3d', 'physics'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Unity Developer',
        'description': 'Build games and interactive experiences using Unity game engine.',
        'required_skills': ['Unity', 'C#', 'Game Development', '3D', 'Scripting'],
        'keywords': ['unity', 'game', 'c#', '3d', 'engine'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Unreal Engine Developer',
        'description': 'Create high-fidelity games and simulations using Unreal Engine.',
        'required_skills': ['Unreal Engine', 'C++', 'Blueprints', '3D', 'Game Development'],
        'keywords': ['unreal', 'c++', 'blueprints', '3d', 'game'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'AR/VR Developer',
        'description': 'Build augmented and virtual reality experiences and applications.',
        'required_skills': ['Unity', 'C#', 'AR/VR', '3D', 'Spatial Computing'],
        'keywords': ['ar', 'vr', 'unity', 'spatial', 'immersive'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Embedded Systems Engineer',
        'description': 'Develop software for embedded systems and IoT devices.',
        'required_skills': ['C', 'C++', 'Embedded Systems', 'Microcontrollers', 'IoT'],
        'keywords': ['embedded', 'c', 'c++', 'microcontroller', 'iot'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'IoT Developer',
        'description': 'Build Internet of Things solutions and connected device applications.',
        'required_skills': ['Python', 'IoT', 'Arduino', 'MQTT', 'Cloud'],
        'keywords': ['iot', 'arduino', 'connected', 'sensors', 'cloud'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Robotics Engineer',
        'description': 'Design and program robots for automation and industrial applications.',
        'required_skills': ['Python', 'ROS', 'C++', 'Robotics', 'Automation'],
        'keywords': ['robotics', 'ros', 'automation', 'c++', 'python'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Network Engineer',
        'description': 'Design, implement, and maintain network infrastructure and security.',
        'required_skills': ['Networking', 'Cisco', 'Firewalls', 'VPN', 'TCP/IP'],
        'keywords': ['network', 'cisco', 'firewall', 'routing', 'switching'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'System Administrator',
        'description': 'Manage and maintain server systems, operating systems, and IT infrastructure.',
        'required_skills': ['Linux', 'Windows Server', 'Scripting', 'Networking', 'Virtualization'],
        'keywords': ['sysadmin', 'linux', 'windows', 'server', 'infrastructure'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Technical Support Engineer',
        'description': 'Provide technical support and troubleshooting for software and hardware issues.',
        'required_skills': ['Troubleshooting', 'Communication', 'Windows', 'Linux', 'Networking'],
        'keywords': ['support', 'troubleshooting', 'helpdesk', 'customer service', 'technical'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Technical Writer',
        'description': 'Create technical documentation, user guides, and API documentation.',
        'required_skills': ['Technical Writing', 'Documentation', 'Communication', 'Markdown', 'APIs'],
        'keywords': ['technical writing', 'documentation', 'api docs', 'guides', 'communication'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Product Manager',
        'description': 'Define product strategy, roadmap, and features to deliver user value.',
        'required_skills': ['Product Management', 'Agile', 'Roadmapping', 'User Research', 'Analytics'],
        'keywords': ['product', 'roadmap', 'agile', 'strategy', 'user research'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Project Manager',
        'description': 'Plan, execute, and manage projects to deliver on time and within budget.',
        'required_skills': ['Project Management', 'Agile', 'Scrum', 'Communication', 'JIRA'],
        'keywords': ['project', 'agile', 'scrum', 'planning', 'jira'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Scrum Master',
        'description': 'Facilitate Scrum processes and help teams deliver value incrementally.',
        'required_skills': ['Scrum', 'Agile', 'Facilitation', 'Coaching', 'JIRA'],
        'keywords': ['scrum', 'agile', 'facilitation', 'coaching', 'sprint'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'UX Researcher',
        'description': 'Conduct user research to understand user needs and improve product experiences.',
        'required_skills': ['User Research', 'Usability Testing', 'Interviews', 'Analytics', 'Communication'],
        'keywords': ['ux research', 'user testing', 'interviews', 'usability', 'research'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'UX Designer',
        'description': 'Design user-centered experiences through wireframes, prototypes, and user flows.',
        'required_skills': ['UX Design', 'Figma', 'Prototyping', 'User Research', 'Wireframing'],
        'keywords': ['ux design', 'figma', 'prototyping', 'wireframes', 'user flows'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'UI Designer',
        'description': 'Create visually appealing user interfaces with strong design principles.',
        'required_skills': ['UI Design', 'Figma', 'Adobe XD', 'Color Theory', 'Typography'],
        'keywords': ['ui design', 'figma', 'visual', 'typography', 'color'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Graphic Designer',
        'description': 'Create visual content for digital and print media using design tools.',
        'required_skills': ['Graphic Design', 'Adobe Photoshop', 'Adobe Illustrator', 'Typography', 'Branding'],
        'keywords': ['graphic design', 'photoshop', 'illustrator', 'visual', 'branding'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Motion Designer',
        'description': 'Create animated content and motion graphics for digital media.',
        'required_skills': ['Motion Graphics', 'After Effects', 'Animation', 'Video Editing', 'Design'],
        'keywords': ['motion', 'animation', 'after effects', 'video', 'graphics'],
        'experience_level': 'Intermediate',
    },
    {
        'title': '3D Artist',
        'description': 'Create 3D models, textures, and assets for games, films, and visualization.',
        'required_skills': ['3D Modeling', 'Blender', 'Maya', 'Texturing', 'Rendering'],
        'keywords': ['3d', 'blender', 'maya', 'modeling', 'rendering'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Video Editor',
        'description': 'Edit and produce video content for various platforms and purposes.',
        'required_skills': ['Video Editing', 'Premiere Pro', 'After Effects', 'Storytelling', 'Audio'],
        'keywords': ['video editing', 'premiere', 'after effects', 'storytelling', 'production'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Digital Marketing Specialist',
        'description': 'Execute digital marketing campaigns across SEO, SEM, social media, and email.',
        'required_skills': ['Digital Marketing', 'SEO', 'Google Analytics', 'Social Media', 'Content Marketing'],
        'keywords': ['digital marketing', 'seo', 'analytics', 'social media', 'campaigns'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'SEO Specialist',
        'description': 'Optimize websites and content for search engine visibility and ranking.',
        'required_skills': ['SEO', 'Keyword Research', 'Google Analytics', 'Content Strategy', 'Technical SEO'],
        'keywords': ['seo', 'keyword research', 'analytics', 'ranking', 'optimization'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Social Media Manager',
        'description': 'Manage social media presence, content, and engagement strategies.',
        'required_skills': ['Social Media', 'Content Creation', 'Analytics', 'Community Management', 'Marketing'],
        'keywords': ['social media', 'content', 'community', 'engagement', 'marketing'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Content Writer',
        'description': 'Create engaging content for websites, blogs, marketing materials, and documentation.',
        'required_skills': ['Content Writing', 'SEO', 'Research', 'Editing', 'Communication'],
        'keywords': ['content writing', 'copywriting', 'seo', 'blogging', 'editing'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Copywriter',
        'description': 'Write persuasive copy for advertising, marketing, and brand communications.',
        'required_skills': ['Copywriting', 'Creative Writing', 'Marketing', 'Brand Voice', 'Editing'],
        'keywords': ['copywriting', 'creative writing', 'advertising', 'brand', 'marketing'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'HR Manager',
        'description': 'Manage human resources functions including recruitment, employee relations, and compliance.',
        'required_skills': ['HR Management', 'Recruitment', 'Employee Relations', 'Compliance', 'Communication'],
        'keywords': ['hr', 'recruitment', 'employee relations', 'compliance', 'management'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Recruiter',
        'description': 'Source, screen, and hire candidates for open positions across organizations.',
        'required_skills': ['Recruitment', 'Sourcing', 'Interviewing', 'ATS', 'Communication'],
        'keywords': ['recruiting', 'sourcing', 'interviewing', 'hiring', 'talent'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Technical Recruiter',
        'description': 'Specialize in recruiting technical talent for engineering and IT roles.',
        'required_skills': ['Technical Recruitment', 'Sourcing', 'Technical Assessment', 'Networking', 'Communication'],
        'keywords': ['technical recruiting', 'engineering', 'sourcing', 'talent', 'it'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Data Entry Specialist',
        'description': 'Accurately input and manage data in databases and systems.',
        'required_skills': ['Data Entry', 'Typing', 'Excel', 'Attention to Detail', 'Accuracy'],
        'keywords': ['data entry', 'typing', 'excel', 'accuracy', 'database'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Virtual Assistant',
        'description': 'Provide administrative support remotely including scheduling, email, and coordination.',
        'required_skills': ['Administrative Support', 'Communication', 'Time Management', 'Organization', 'Google Suite'],
        'keywords': ['virtual assistant', 'admin', 'scheduling', 'organization', 'support'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Customer Service Representative',
        'description': 'Provide customer support and resolve inquiries through various channels.',
        'required_skills': ['Customer Service', 'Communication', 'Problem Solving', 'CRM', 'Patience'],
        'keywords': ['customer service', 'support', 'communication', 'problem solving', 'crm'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Sales Representative',
        'description': 'Drive sales through prospecting, presenting, and closing deals with customers.',
        'required_skills': ['Sales', 'Communication', 'Negotiation', 'CRM', 'Presentation'],
        'keywords': ['sales', 'negotiation', 'prospecting', 'closing', 'crm'],
        'experience_level': 'Fresher',
    },
    {
        'title': 'Account Manager',
        'description': 'Manage client relationships and ensure customer satisfaction and retention.',
        'required_skills': ['Account Management', 'Communication', 'Relationship Building', 'CRM', 'Problem Solving'],
        'keywords': ['account management', 'client relations', 'retention', 'communication', 'crm'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Business Development Manager',
        'description': 'Identify and pursue new business opportunities and partnerships.',
        'required_skills': ['Business Development', 'Sales', 'Strategy', 'Networking', 'Communication'],
        'keywords': ['business development', 'sales', 'strategy', 'partnerships', 'growth'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Financial Analyst',
        'description': 'Analyze financial data and provide insights for business decisions.',
        'required_skills': ['Financial Analysis', 'Excel', 'Modeling', 'Accounting', 'Reporting'],
        'keywords': ['financial analysis', 'excel', 'modeling', 'accounting', 'reporting'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Accountant',
        'description': 'Manage financial records, prepare financial statements, and ensure compliance.',
        'required_skills': ['Accounting', 'Excel', 'Financial Reporting', 'Tax', 'Compliance'],
        'keywords': ['accounting', 'financial reporting', 'tax', 'compliance', 'bookkeeping'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Operations Manager',
        'description': 'Oversee daily operations and improve efficiency and productivity.',
        'required_skills': ['Operations Management', 'Process Improvement', 'Leadership', 'Analytics', 'Communication'],
        'keywords': ['operations', 'management', 'process improvement', 'efficiency', 'leadership'],
        'experience_level': 'Intermediate',
    },
    {
        'title': 'Supply Chain Manager',
        'description': 'Manage supply chain operations, logistics, and inventory.',
        'required_skills': ['Supply Chain', 'Logistics', 'Inventory Management', 'Procurement', 'Analytics'],
        'keywords': ['supply chain', 'logistics', 'inventory', 'procurement', 'operations'],
        'experience_level': 'Intermediate',
    },
]


class Command(BaseCommand):
    help = 'Seed default job roles for the AI Resume Analyzer project.'

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for item in JOB_ROLES:
            _, was_created = JobRole.objects.update_or_create(
                title=item['title'],
                defaults=item,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seed complete. Created: {created}, Updated: {updated}'
        ))
