# Generated by Django 4.2.30 on 2026-06-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_hint', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('HR', 'HR'), ('PROJECT', 'Project'), ('CODING', 'Coding')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='jobs.jobrole')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
